/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ManifoldSubscriptionList {
    'clientId'?: string;
  }
}

declare global {


  interface HTMLManifoldSubscriptionListElement extends Components.ManifoldSubscriptionList, HTMLStencilElement {}
  var HTMLManifoldSubscriptionListElement: {
    prototype: HTMLManifoldSubscriptionListElement;
    new (): HTMLManifoldSubscriptionListElement;
  };
  interface HTMLElementTagNameMap {
    'manifold-subscription-list': HTMLManifoldSubscriptionListElement;
  }
}

declare namespace LocalJSX {
  interface ManifoldSubscriptionList {
    'clientId'?: string;
  }

  interface IntrinsicElements {
    'manifold-subscription-list': ManifoldSubscriptionList;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'manifold-subscription-list': LocalJSX.ManifoldSubscriptionList & JSXBase.HTMLAttributes<HTMLManifoldSubscriptionListElement>;
    }
  }
}


