name: prerelease

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - id: tag
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/v}
      - run: npm run version -- ${{ steps.tag.outputs.TAG }}
      - run: npm run changelog:release -- ${{ steps.tag.outputs.TAG }}
      - run: make package
      - run: 'echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc'
      - run: 'npm publish ./pkg --tag next'
  cdn:
    env:
      BUCKET: manifold-js
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      PACKAGE: '@manifoldco/manifold-invoices' # package name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true
      - run: npm install
      - run: make package
      # Manually specify all files/folders to copy over (for reference see .npmignore)
      - run:
          gsutil -m cp -r ${GITHUB_WORKSPACE}/pkg
          gs://${BUCKET}/${PACKAGE}@${GITHUB_REF#refs/tags/v}
      # Note: DON’T publish a prerelease to the main folder like we would with a release!
